### ISSUE TITLE
run failed

### ISSUE THREAD

**Issue by powersam** [MarquezProject/marquez-web#110]
[BEGIN] 7/14/2020 1:33:27 AM
[root@instance-20200713-1004 marquez-web]# npm run dev

> marquez-ui@0.1.0 dev /u01/marquezweb/marquez-web
> webpack-dev-server --open --config webpack.dev.js

[HPM] Proxy created: /api  ->  http://localhost:5000
[HPM] Subscribed to http-proxy events:  [ 'error', 'close' ]
? ?wds?: Project is running at http://localhost:1337/
? ?wds?: webpack output is served from /
? ?wds?: Content not from webpack is served from /u01/marquezweb/marquez-web/src
? ?wds?: 404s will fallback to ./index.html
? ?atl?: Using typescript@3.9.6 from typescript
? ?atl?: Using tsconfig.json from /u01/marquezweb/marquez-web/tsconfig.json
? ?atl?: Checking started in a separate process...
? ?atl?: Time: 2037ms
? ?wdm?: Hash: e2ecc7bba86ffa81fd11
Version: webpack 4.43.0
Time: 19724ms
Built at: 07/14/2020 1:33:52 AM
               Asset      Size  Chunks             Chunk Names
           bundle.js  11.9 MiB    main  [emitted]  main
img/marquez-logo.png  4.78 KiB          [emitted]  
Entrypoint main = bundle.js
[0] multi (webpack)-dev-server/client?http://localhost:1337 ./src/index.tsx 40 bytes {main} [built]
[./node_modules/react-dom/index.js] 1.33 KiB {main} [built]
[./node_modules/react-vis/dist/style.css] 1.17 KiB {main} [built]
[./node_modules/react/index.js] 190 bytes {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:1337] (webpack)-dev-server/client?http://localhost:1337 4.29 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {main} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {main} [built]
[./node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {main} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./src/components/App.tsx] 6.05 KiB {main} [built]
[./src/index.tsx] 1.33 KiB {main} [built]
    + 1049 hidden modules
? ?wdm?: Compiled successfully.
Error from chokidar (/u01/marquezweb/marquez-web/node_modules/@material-ui/icons): Error: watch /u01/marquezweb/marquez-web/node_modules/@material-ui/icons/Minimize.js ENOSPC
Error from chokidar (/u01/marquezweb/marquez-web/node_modules/@material-ui/icons): Error: watch /u01/marquezweb/marquez-web/node_modules/@material-ui/icons/MinimizeOutlined.js ENOSPC
Error from chokidar (/u01/marquezweb/marquez-web/node_modules/@material-ui/icons): Error: watch /u01/marquezweb/marquez-web/node_modules/@material-ui/icons/MinimizeOutlined.d.ts ENOSPC
Error from chokidar (/u01/marquezweb/marquez-web/node_modules/@material-ui/icons): Error: watch /u01/marquezweb/marquez-web/node_modules/@material-ui/icons/MinimizeRounded.d.ts ENOSPC
Error from chokidar (/u01/marquezweb/marquez-web/node_modules/@material-ui/icons): Error: watch /u01/marquezweb/marquez-web/node_modules/@material-ui/icons/MinimizeRounded.js ENOSPC
Error from chokidar (/u01/marquezweb/marquez-web/node_modules/@material-ui/icons): Error: watch /u01/marquezweb/marquez-web/node_modules/@material-ui/icons/MinimizeSharp.d.ts ENOSPC
Error from chokidar (/u01/marquezweb/marquez-web/node_modules/@material-ui/icons): Error: watch /u01/marquezweb/marquez-web/node_modules/@material-ui/icons/MinimizeSharp.js ENOSPC
Error from chokidar (/u01/marquezweb/marquez-web/node_modules/@material-ui/icons): Error: watch /u01/marquezweb/marquez-web/node_modules/@material-ui/icons/MinimizeTwoTone.d.ts ENOSPC
Error from chokidar (/u01/marquezweb/marquez-web/node_modules/@material-ui/icons): Error: watch /u01/marquezweb/marquez-web/node_modules/@material-ui/icons/MissedVideoCall.d.ts ENOSPC
Error from chokidar (/u01/marquezweb/marquez-web/node_modules/@material-ui/icons): Error: watch /u01/marquezweb/marquez-web/node_modules/@material-ui/icons/MissedVideoCallOutlined.d.ts ENOSPC
Error from chokidar (/u01/marquezweb/marquez-web/node_modules/@material-ui/icons): Error: watch /u01/marquezweb/marquez-web/node_modules/@material-ui/icons/MissedVideoCall.js ENOSPC
Error from chokidar (/u01/marquezweb/marquez-web/node_modules/@material-ui/icons): Error: watch /u01/marquezweb/marquez-web/node_modules/@material-ui/icons/MissedVideoCallOutlined.js ENOSPC
Error from chokidar (/u01/marquezweb/marquez-web/node_modules/@material-ui/icons): Error: watch /u01/marquezweb/marquez-web/node_modules/@material-ui/icons/MinimizeTwoTone.js ENOSPC

**Comment by wslulciuc** [comment]
@powersam: We are moving all discussions to https://github.com/MarquezProject/marquez. Let us know if you are still running into this issue.
