### ISSUE TITLE
Feedback link on dashboard is broken when running locally using docker-compose

### ISSUE THREAD

**Issue by ankitcha** [MarquezProject/marquez-web#44]
Not sure if this is expected for local setup

**Comment by wslulciuc** [comment]
@ankitcha Thanks for opening this issue! For a local setup, maybe not, but we should provide a way to make the feedback link configurable. @mell0kat would be great to get your thoughts on this!

**Comment by mell0kat** [comment]
Ah yes I do remember discussing this, and I agree.  It should be fairly trivial to do this as well.  I will assign this issue to myself. Thanks for catching this @ankitcha

**Comment by wslulciuc** [comment]
@mell0kat Great! Maybe we can define an environment variable `FEEDBACK_URL`?

**Comment by wslulciuc** [comment]
@mell0kat Would be great to add support for a configurable feedback link. Any updates on adding `FEEDBACK_URL`?

**Comment by mell0kat** [comment]
@wslulciuc / @grantdfoster / @jhubley -- currently this is what I see when I click the link when running via `npm run dev`.  Anyone know what's up here? Or have a different link I can try?

<img width="689" alt="Screen Shot 2020-03-08 at 10 21 35 AM" src="https://user-images.githubusercontent.com/14907923/76164624-c92c5a00-6126-11ea-80df-ef86bab50ea3.png">

**Comment by wslulciuc** [comment]
> Anyone know what's up here? Or have a different link I can try?

Thanks for looking into this, @mell0kat! Sure, we'll have to create a valid google form that we can test against (the one checked in is a mocked link).

I can create a simple form for you to use, or if you wanted create one yourself that also works. Just let me know what you prefer. We can then set `FEEDBACK_URL` to point to that form and test that it can be overwritten.

**Comment by mell0kat** [comment]
Oh hahah I guess the `1234` should have given it away.

I don't mind making the form, but I suppose this is a good time to (re)consider exactly what we want feedback on / what the questions should be.

@wslulciuc / @grantdfoster / @jhubley What are your thoughts on this?  (Maybe we should move this conversation to gitter)

**Comment by wslulciuc** [comment]
@mell0kat For context, let's continue our discussion in this issue. But, you do bring up a valid point on how best to gather UI feedback. Each organization that has Marquez deployed might also have their own custom form to gather feedback (most likely the norm). So, I propose the following 2 options: 

1. Only display the _Feedback_ button when `FEEDBACK_URL` is set. Allowing an organization to use  their own custom form.
2. Define a global UI feedback form that ships with the UI, but can overwritten with `FEEDBACK_URL`

/cc @grantdfoster @jhubley
