### ISSUE TITLE
Default page when no columns exist for a table

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez-web#50]
When the schema for a table has not yet been cataloged in Marquez, the user is presented with a _blank_ screen (see below). We may want to provide some default message, like _schema not present_ or similar to indicate the absents of the schema?

<img width="1280" alt="Screen Shot 2020-01-22 at 1 29 07 PM" src="https://user-images.githubusercontent.com/1553185/72936145-7b48c780-3d1b-11ea-8cf1-803e4b4cde13.png">

@grantdfoster, @jhubley It be great to get your thoughts!

**Comment by jhubley** [comment]
Totally, there should be a message. Changing to a bug and assigning to myself. Thanks!

**Comment by jhubley** [comment]
fixed!
