### ISSUE TITLE
Define popular datasets

### ISSUE THREAD

**Issue by jhubley** [MarquezProject/marquez-web#63]
Right now, on load, a "popular datasets" label shows, but this isn't actually defined-- all the datasets load. So we need to calculate the number of edges for each, and then filter the datasets so we're only showing those that have an edge count in the top ten percent.

**Comment by wslulciuc** [comment]
Thanks for opening this issue, @jhubley! Your approach makes sense. We have been discussing authoring a Lineage API proposal for Marquez which can answer questions like: _What are the top N datasets_? For example, using a combination of arguments `filter` and `limit` to return a list of top datasets:

```
GET /api/v1/lineage?filters=top&limit=10
```
```
{
  "datasets": [ ... ]
}
```

I'm cool with adding the "top datasets" logic to the UI as a short term solution (that way this feature isn't blocked). Let me know your thoughts!

**Comment by jhubley** [comment]
Awesome, Lineage API sounds excellent.
I'll implement the 'top datasets' logic for now because it's not much work. Thanks!
