### ISSUE TITLE
Marquez logo not loading

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez-web#67]
<img width="355" alt="Screen Shot 2020-02-27 at 12 49 21 PM" src="https://user-images.githubusercontent.com/1553185/75485494-a1d3d100-595f-11ea-8adc-d541e6d36848.png">

**Comment by wslulciuc** [comment]
@jhubley Any ideas on what the issue might be? Thanks!

**Comment by jhubley** [comment]
ah, just need to update the path. will do this today or tomorrow am!

**Comment by wslulciuc** [comment]
@jhubley Awesome! I'll assign this issue to you.

**Comment by wslulciuc** [comment]
@jhubley Have you had a chance to look into this issue? I'd be great to release `0.5.0` of the UI!

**Comment by wslulciuc** [comment]
Fixed #82
