### ISSUE TITLE
504 when opening Marquez Web on Docker

### ISSUE THREAD

**Issue by allansene** [MarquezProject/marquez-web#76]
Guys,

I'm trying to test Marquez but, after spinning up the Marquez Docker Compose and Marquez Web Docker, I'm having this error on the UI:

![image](https://user-images.githubusercontent.com/6767685/77679577-7d284480-6f71-11ea-9fb2-448250031215.png)

The Operational Menu (localhost:5001) seems to be ok. All healthy.

Where goes the logs from the marquez-web docker
```
[HPM] Proxy created: /api/v1  -> http://undefined:undefined/
App listening on port 3000!
[HPM] Error occurred while trying to proxy request /api/v1/namespaces from localhost:3000 to http://undefined:undefined/ (ENOTFOUND) (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

**Comment by wslulciuc** [comment]
Hey, @allansene 👋. Great to see you're exploring Marquez! Sure, happy to help here. Are you bringing up the Marquez backend + UI using the [compose file at the project root](https://github.com/MarquezProject/marquez-web/blob/master/docker-compose.yml)? That's the easiest way to get up and running.

Let me know if you took other steps to get started.

**Comment by gvisniuc** [comment]
Indeed as @wslulciuc said, you need to start the services using docker-compose, since the that single docker container will only start the web interface and not the API.
Also in my cases I needed to run it a few times (3), seems that the current waiting time is not long enough for the db to be seeded.

**Comment by brucekissinger** [comment]
I'm having the same problem on a new install.  The Marquez backend and admin UI come up just fine.  I can use the API successfully.  But the Marquez web application has an error in the logs like:

[HPM] Error occurred while trying to proxy request /api/v1/namespaces from <my server name>:3000 to http://undefined:undefined/ (EAI_AGAIN) (https://nodejs.org/api/errors.html#errors_common_system_errors)

I've tried stopping and restarting both the backend and the web client several times, but the error seems to be consistent.

**Comment by wslulciuc** [comment]
@allansene @gvisniuc @brucekissinger: We are moving all discussions to https://github.com/MarquezProject/marquez. Please let us know if you are still running into any issues!
