### ISSUE TITLE
UI fails to load

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez-web#84]
@grantdfoster The UI fails to load on `docker-compose up`.  May be the result of merging #83?

<img width="1396" alt="Screen Shot 2020-04-02 at 8 31 43 AM" src="https://user-images.githubusercontent.com/1553185/78268003-7abb7280-74bc-11ea-981b-9cd6475bd0a5.png">

**Comment by jharris126** [comment]
I think this has been an issue since the #80 and #81 changes were merged. The UI loads when you have just datasets loaded into marquez but no jobs. Once you link them with jobs, it breaks. I figured I had an issue with my python script that bulk loads jobs and was investigating when I saw this issue come through. Hope this helps!

**Comment by grantfosterdev** [comment]
hm... i will admit we have not tested the UI with JUST datasets or JUST jobs loaded... can definitely look into that but up until now our assumption was that every instance would have at least one job and one dataset -- I guess not!

@wslulciuc, that's with the docker-compose up --build command?  I just tested (again) on my end and it works (we even pushed a new version to WeWork production environment and THAT works too!)

**Comment by jharris126** [comment]
@grantdfoster totally a safe assumption to make. I just have a series of 3 scripts that make API calls to load the data whenever I do a clean build. I run the sources script then the datasets script then the jobs script. I just happened to check the UI between scripts and didn't experience the blank UI problem until I loaded the jobs. I assume that means the issue has something to do with the lineage chart assembling the dependencies.

I'm only using the docker-compose up --build command and running on a laptop, so I can't speak to any other deployment method.

**Comment by grantfosterdev** [comment]
@jharris126 interesting, will take a look at doing that incrementally and seeing what I find.  Still confused at @wslulciuc 's docker-compose up issue (latest master code is working for me), luckily we're jumping on a call today and can talk it out.

**Comment by wslulciuc** [comment]
@grantdfoster This was very much a user error "bug"! I added `docker/up.sh` (see #86) that wraps `docker-compose` to force recreate containers and volumes. This fixed the UI error I was seeing 😄 

@jharris126 It'd be great if you could review / try the fix in #86!
