### ISSUE TITLE
Fix lineage graph routing

### ISSUE THREAD

**Issue by wslulciuc** [MarquezProject/marquez-web#87]
Let's reduce graph load time by not doing a full page refresh on lineage graph node select.

**Comment by grantfosterdev** [comment]
@mell0kat we need to remove the href assignments on the nodes in the lineage and wrap each node instead in a <Link /> React component.  Currently the href is taking you out of the app and then back in... increasing loading time and jeopardizing the UX.  

We are using the <Link /> logic in the home page cards and should mimic that I think, but I wasn't entirely sure how to implement that functionality with our node / D3 setup.

**Comment by wslulciuc** [comment]
Fixed #101
