### ISSUE TITLE
Expanded lineage options

### ISSUE THREAD

**Issue by jharris126** [MarquezProject/marquez-web#91]
Now that I have my entire data catalog loaded into my Marquez prototype, I seem to have outgrown the lineage canvas. I was thinking a pop out window (like the expanded SQL window Jobs have) that allows both scrolling and zooming would be cool, but whatever allows me to explore and link through my entire lineage is ok by me.

<img width="1298" alt="Screen Shot 2020-04-22 at 3 29 04 PM" src="https://user-images.githubusercontent.com/22508179/80040813-bc35b100-84af-11ea-8aca-e28c8e7378ff.png">

**Comment by wslulciuc** [comment]
@jharris126: We are moving all discussions to https://github.com/MarquezProject/marquez. We be moving your issue there to continue the discussion!
