### ISSUE TITLE
Dataset Fields and Descriptions lose cohesion when a "long" title is supplied

### ISSUE THREAD

**Issue by frankcash** [MarquezProject/marquez-web#95]
## Version 

`marquezproject/marquez-web:0.5.0`

## Expected behavior:

Field and description will always line-up

## Actual behavior:

![Screen Shot 2020-05-06 at 8 55 56 AM](https://user-images.githubusercontent.com/6012231/81179270-6ebd4780-8f77-11ea-8ff3-9c42748898f2.png)

**Comment by wslulciuc** [comment]
@frankcash: We are moving all discussions to https://github.com/MarquezProject/marquez. We'll be moving your issue there to continue the discussion!
