### ISSUE TITLE
is_pii flag doesn't work because the back end always sets tags to be all caps

### ISSUE THREAD

**Issue by frankcash** [MarquezProject/marquez-web#96]
The `is_pii` logo can never be set as long as the back end sets the value to all capital and the key search doesn't capitalize everything in a similar manner

https://github.com/MarquezProject/marquez/blob/6703d22be0833e5be9217e885e951876f4f13f40/src/main/java/marquez/service/models/Tag.java#L30

**Comment by wslulciuc** [comment]
Fixed #99
